cargo-features = ["workspace-inheritance"]

[package]
name = "clap_derive"
version.workspace = true
edition.workspace = true
include.workspace = true
description = "Parse command line argument by defining a struct, derive crate."
repository = "https://github.com/clap-rs/clap/tree/master/clap_derive"
documentation = "https://docs.rs/clap_derive"
keywords = [
	"clap",
	"cli",
	"parse",
	"derive",
	"proc_macro"
]
categories = ["command-line-interface", "development-tools::procedural-macro-helpers"]
license.workspace = true
readme = "README.md"

[package.metadata.release]
shared-version = true
dependent-version = "upgrade"
tag-name = "v{{version}}"
pre-release-replacements = [
  {file="README.md", search="github.com/clap-rs/clap/blob/[^/]+/", replace="github.com/clap-rs/clap/blob/{{tag_name}}/", exactly=2, prerelease = true},
]

[lib]
proc-macro = true
bench = false

[dependencies]
syn = { version = "1.0.74", features = ["full"] }
quote = "1.0.9"
proc-macro2 = "1.0.28"
heck = "0.4.0"
proc-macro-error = "1"

[features]
default = []
debug = []
unstable-v4 = []

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
